import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PorscheDesignSystemProvider } from "@porsche-design-system/components-react/ssr";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PorscheDesignSystemProvider>{children}</PorscheDesignSystemProvider>;
      </body>
    </html>
  );
}
